const tintColorLight = '#4ECDC4';
const tintColorDark = '#4ECDC4';

export const Colors = {
  light: {
    text: '#2C3E50',
    background: '#F8FFFE',
    tint: tintColorLight,
    icon: '#7F8C8D',
    tabIconDefault: '#95A5A6',
    tabIconSelected: tintColorLight,
    primary: '#4ECDC4',
    secondary: '#E8F5F4',
    accent: '#BDC3C7',
    card: '#FFFFFF',
    border: '#D5DBDB',
    notification: '#E74C3C',
    success: '#27AE60',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#3498DB',
    // إضافات للثيم الموحد
    headerBackground: '#4ECDC4',
    headerText: '#FFFFFF',
    buttonPrimary: '#4ECDC4',
    buttonSecondary: '#E8F5F4',
    buttonText: '#FFFFFF',
    buttonTextSecondary: '#2C3E50',
    inputBackground: '#FFFFFF',
    inputBorder: '#D5DBDB',
    inputText: '#2C3E50',
    placeholderText: '#95A5A6',
    divider: '#E8E8E8',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.5)',
    cardShadow: '#BDC3C7',
    toolbarBackground: '#FFFFFF',
    toolbarBorder: '#E0E0E0',
    alternateBackground: '#F5F6FA',
  },
  dark: {
    text: '#2C3E50',
    background: '#F8FFFE',
    tint: tintColorLight,
    icon: '#7F8C8D',
    tabIconDefault: '#95A5A6',
    tabIconSelected: tintColorLight,
    primary: '#4ECDC4',
    secondary: '#E8F5F4',
    accent: '#BDC3C7',
    card: '#FFFFFF',
    border: '#D5DBDB',
    notification: '#E74C3C',
    success: '#27AE60',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#3498DB',
    // نفس الألوان للوضع المظلم (يمكن تخصيصها لاحقاً)
    headerBackground: '#4ECDC4',
    headerText: '#FFFFFF',
    buttonPrimary: '#4ECDC4',
    buttonSecondary: '#E8F5F4',
    buttonText: '#FFFFFF',
    buttonTextSecondary: '#2C3E50',
    inputBackground: '#FFFFFF',
    inputBorder: '#D5DBDB',
    inputText: '#2C3E50',
    placeholderText: '#95A5A6',
    divider: '#E8E8E8',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.5)',
    cardShadow: '#BDC3C7',
    toolbarBackground: '#FFFFFF',
    toolbarBorder: '#E0E0E0',
    alternateBackground: '#F5F6FA',
  },
};

// أنماط موحدة للتطبيق
export const GlobalStyles = {
  // أنماط الهيدر
  header: {
    backgroundColor: Colors.light.headerBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold' as const,
    color: Colors.light.headerText,
    textAlign: 'center' as const,
    flex: 1,
    writingDirection: 'rtl' as const,
  },
  headerButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },

  // أنماط الأزرار
  primaryButton: {
    backgroundColor: Colors.light.buttonPrimary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  secondaryButton: {
    backgroundColor: Colors.light.buttonSecondary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  primaryButtonText: {
    color: Colors.light.buttonText,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },
  secondaryButtonText: {
    color: Colors.light.buttonTextSecondary,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط البطاقات
  card: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    shadowColor: Colors.light.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },

  // أنماط المدخلات
  textInput: {
    backgroundColor: Colors.light.inputBackground,
    borderWidth: 1,
    borderColor: Colors.light.inputBorder,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: Colors.light.inputText,
    textAlign: 'right' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط شريط الأدوات
  toolbar: {
    flexDirection: 'row' as const,
    backgroundColor: Colors.light.toolbarBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.toolbarBorder,
    gap: 5,
  },
  toolButton: {
    flex: 1,
    alignItems: 'center' as const,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 8,
    backgroundColor: Colors.light.alternateBackground,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  toolButtonText: {
    fontSize: 10,
    color: Colors.light.text,
    marginTop: 2,
    textAlign: 'center' as const,
    fontWeight: '500' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط عامة
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.light.divider,
    marginVertical: 16,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: Colors.light.placeholderText,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
  },
};