
const tintColorLight = '#add6d7';
const tintColorDark = '#cadcd9';

export const Colors = {
  light: {
    text: '#100f0d',
    background: '#f2fafa',
    tint: tintColorLight,
    icon: '#5a5b58',
    tabIconDefault: '#9a9a95',
    tabIconSelected: tintColorLight,
    primary: '#add6d7',
    secondary: '#e0f0f1',
    accent: '#cadfde',
    card: '#f2fafa',
    border: '#cadcd9',
    notification: '#E74C3C',
    success: '#add4ce',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#bcebec',
    // إضافات للثيم الموحد
    headerBackground: '#add6d7',
    headerText: '#100f0d',
    buttonPrimary: '#add6d7',
    buttonSecondary: '#e0f0f1',
    buttonText: '#100f0d',
    buttonTextSecondary: '#100f0d',
    inputBackground: '#f2fafa',
    inputBorder: '#cadcd9',
    inputText: '#100f0d',
    placeholderText: '#9a9a95',
    divider: '#cadfde',
    shadow: '#5a5b58',
    overlay: 'rgba(16, 15, 13, 0.5)',
    cardShadow: '#cadfde',
    toolbarBackground: '#e0f0f1',
    toolbarBorder: '#cadcd9',
    alternateBackground: '#bcebec',
  },
  dark: {
    text: '#f2fafa',
    background: '#100f0d',
    tint: tintColorDark,
    icon: '#9a9a95',
    tabIconDefault: '#5a5b58',
    tabIconSelected: tintColorDark,
    primary: '#cadcd9',
    secondary: '#5a5b58',
    accent: '#9a9a95',
    card: '#5a5b58',
    border: '#9a9a95',
    notification: '#E74C3C',
    success: '#add4ce',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#bcebec',
    // ألوان للوضع المظلم
    headerBackground: '#cadcd9',
    headerText: '#100f0d',
    buttonPrimary: '#cadcd9',
    buttonSecondary: '#5a5b58',
    buttonText: '#100f0d',
    buttonTextSecondary: '#f2fafa',
    inputBackground: '#5a5b58',
    inputBorder: '#9a9a95',
    inputText: '#f2fafa',
    placeholderText: '#9a9a95',
    divider: '#9a9a95',
    shadow: '#100f0d',
    overlay: 'rgba(242, 250, 250, 0.5)',
    cardShadow: '#9a9a95',
    toolbarBackground: '#5a5b58',
    toolbarBorder: '#9a9a95',
    alternateBackground: '#9a9a95',
  },
};

// أنماط موحدة للتطبيق
export const GlobalStyles = {
  // أنماط الهيدر
  header: {
    backgroundColor: Colors.light.headerBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold' as const,
    color: Colors.light.headerText,
    textAlign: 'center' as const,
    flex: 1,
    writingDirection: 'rtl' as const,
  },
  headerButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },

  // أنماط الأزرار
  primaryButton: {
    backgroundColor: Colors.light.buttonPrimary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  secondaryButton: {
    backgroundColor: Colors.light.buttonSecondary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  primaryButtonText: {
    color: Colors.light.buttonText,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },
  secondaryButtonText: {
    color: Colors.light.buttonTextSecondary,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط البطاقات
  card: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    shadowColor: Colors.light.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },

  // أنماط المدخلات
  textInput: {
    backgroundColor: Colors.light.inputBackground,
    borderWidth: 1,
    borderColor: Colors.light.inputBorder,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: Colors.light.inputText,
    textAlign: 'right' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط شريط الأدوات
  toolbar: {
    flexDirection: 'row' as const,
    backgroundColor: Colors.light.toolbarBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.toolbarBorder,
    gap: 5,
  },
  toolButton: {
    flex: 1,
    alignItems: 'center' as const,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 8,
    backgroundColor: Colors.light.alternateBackground,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  toolButtonText: {
    fontSize: 10,
    color: Colors.light.text,
    marginTop: 2,
    textAlign: 'center' as const,
    fontWeight: '500' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط عامة
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.light.divider,
    marginVertical: 16,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: Colors.light.placeholderText,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
  },
};
