const tintColorLight = '#4ECDC4';
const tintColorDark = '#4ECDC4';

// الثيمات المتوفرة
export const Themes = {
  default: {
    name: 'الافتراضي',
    light: {
      text: '#2C3E50',
      background: '#F8FFFE',
      tint: '#4ECDC4',
      icon: '#7F8C8D',
      tabIconDefault: '#95A5A6',
      tabIconSelected: '#4ECDC4',
      primary: '#1B2951',
      secondary: '#E8F5F4',
      accent: '#BDC3C7',
      card: '#FFFFFF',
      border: '#D5DBDB',
      notification: '#E74C3C',
      success: '#27AE60',
      warning: '#F39C12',
      error: '#E74C3C',
      info: '#1c1f33',
      headerBackground: '#4ECDC4',
      headerText: '#FFFFFF',
      buttonPrimary: '#4ECDC4',
      buttonSecondary: '#E8F5F4',
      buttonText: '#FFFFFF',
      buttonTextSecondary: '#2C3E50',
      inputBackground: '#FFFFFF',
      inputBorder: '#D5DBDB',
      inputText: '#2C3E50',
      placeholderText: '#95A5A6',
      divider: '#E8E8E8',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.5)',
      cardShadow: '#BDC3C7',
      toolbarBackground: '#FFFFFF',
      toolbarBorder: '#E0E0E0',
      alternateBackground: '#F5F6FA',
    },
    dark: {
      text: '#ECEFF4',
      background: '#2E3440',
      tint: '#88C0D0',
      icon: '#D8DEE9',
      tabIconDefault: '#81A1C1',
      tabIconSelected: '#88C0D0',
      primary: '#5E81AC',
      secondary: '#3B4252',
      accent: '#4C566A',
      card: '#3B4252',
      border: '#434C5E',
      notification: '#BF616A',
      success: '#A3BE8C',
      warning: '#EBCB8B',
      error: '#BF616A',
      info: '#81A1C1',
      headerBackground: '#2E3440',
      headerText: '#ECEFF4',
      buttonPrimary: '#5E81AC',
      buttonSecondary: '#3B4252',
      buttonText: '#ECEFF4',
      buttonTextSecondary: '#ECEFF4',
      inputBackground: '#3B4252',
      inputBorder: '#434C5E',
      inputText: '#ECEFF4',
      placeholderText: '#81A1C1',
      divider: '#434C5E',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.7)',
      cardShadow: '#2E3440',
      toolbarBackground: '#3B4252',
      toolbarBorder: '#434C5E',
      alternateBackground: '#434C5E',
    }
  },
  ocean: {
    name: 'المحيط',
    light: {
      text: '#1A365D',
      background: '#EBF8FF',
      tint: '#2B6CB0',
      icon: '#2D3748',
      tabIconDefault: '#4A5568',
      tabIconSelected: '#2B6CB0',
      primary: '#2B6CB0',
      secondary: '#BEE3F8',
      accent: '#4299E1',
      card: '#FFFFFF',
      border: '#90CDF4',
      notification: '#F56565',
      success: '#38B2AC',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      headerBackground: '#2B6CB0',
      headerText: '#FFFFFF',
      buttonPrimary: '#2B6CB0',
      buttonSecondary: '#BEE3F8',
      buttonText: '#FFFFFF',
      buttonTextSecondary: '#1A365D',
      inputBackground: '#FFFFFF',
      inputBorder: '#90CDF4',
      inputText: '#1A365D',
      placeholderText: '#4A5568',
      divider: '#90CDF4',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.5)',
      cardShadow: '#4299E1',
      toolbarBackground: '#FFFFFF',
      toolbarBorder: '#90CDF4',
      alternateBackground: '#F7FAFC',
    },
    dark: {
      text: '#E2E8F0',
      background: '#1A202C',
      tint: '#63B3ED',
      icon: '#CBD5E0',
      tabIconDefault: '#A0AEC0',
      tabIconSelected: '#63B3ED',
      primary: '#3182CE',
      secondary: '#2D3748',
      accent: '#4299E1',
      card: '#2D3748',
      border: '#4A5568',
      notification: '#FC8181',
      success: '#4FD1C7',
      warning: '#F6AD55',
      error: '#FC8181',
      info: '#63B3ED',
      headerBackground: '#1A202C',
      headerText: '#E2E8F0',
      buttonPrimary: '#3182CE',
      buttonSecondary: '#2D3748',
      buttonText: '#E2E8F0',
      buttonTextSecondary: '#E2E8F0',
      inputBackground: '#2D3748',
      inputBorder: '#4A5568',
      inputText: '#E2E8F0',
      placeholderText: '#A0AEC0',
      divider: '#4A5568',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.7)',
      cardShadow: '#1A202C',
      toolbarBackground: '#2D3748',
      toolbarBorder: '#4A5568',
      alternateBackground: '#4A5568',
    }
  },
  sunset: {
    name: 'غروب الشمس',
    light: {
      text: '#7C2D12',
      background: '#FFF7ED',
      tint: '#EA580C',
      icon: '#9A3412',
      tabIconDefault: '#C2410C',
      tabIconSelected: '#EA580C',
      primary: '#EA580C',
      secondary: '#FED7AA',
      accent: '#FB923C',
      card: '#FFFFFF',
      border: '#FDBA74',
      notification: '#DC2626',
      success: '#059669',
      warning: '#D97706',
      error: '#DC2626',
      info: '#0284C7',
      headerBackground: '#EA580C',
      headerText: '#FFFFFF',
      buttonPrimary: '#EA580C',
      buttonSecondary: '#FED7AA',
      buttonText: '#FFFFFF',
      buttonTextSecondary: '#7C2D12',
      inputBackground: '#FFFFFF',
      inputBorder: '#FDBA74',
      inputText: '#7C2D12',
      placeholderText: '#C2410C',
      divider: '#FDBA74',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.5)',
      cardShadow: '#FB923C',
      toolbarBackground: '#FFFFFF',
      toolbarBorder: '#FDBA74',
      alternateBackground: '#FEF3C7',
    },
    dark: {
      text: '#FED7AA',
      background: '#431407',
      tint: '#FB923C',
      icon: '#FDBA74',
      tabIconDefault: '#F97316',
      tabIconSelected: '#FB923C',
      primary: '#F97316',
      secondary: '#7C2D12',
      accent: '#EA580C',
      card: '#7C2D12',
      border: '#9A3412',
      notification: '#FCA5A5',
      success: '#6EE7B7',
      warning: '#FCD34D',
      error: '#FCA5A5',
      info: '#7DD3FC',
      headerBackground: '#431407',
      headerText: '#FED7AA',
      buttonPrimary: '#F97316',
      buttonSecondary: '#7C2D12',
      buttonText: '#FED7AA',
      buttonTextSecondary: '#FED7AA',
      inputBackground: '#7C2D12',
      inputBorder: '#9A3412',
      inputText: '#FED7AA',
      placeholderText: '#F97316',
      divider: '#9A3412',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.7)',
      cardShadow: '#431407',
      toolbarBackground: '#7C2D12',
      toolbarBorder: '#9A3412',
      alternateBackground: '#9A3412',
    }
  },
  forest: {
    name: 'الغابة',
    light: {
      text: '#14532D',
      background: '#F0FDF4',
      tint: '#16A34A',
      icon: '#15803D',
      tabIconDefault: '#22C55E',
      tabIconSelected: '#16A34A',
      primary: '#16A34A',
      secondary: '#BBF7D0',
      accent: '#22C55E',
      card: '#FFFFFF',
      border: '#86EFAC',
      notification: '#DC2626',
      success: '#16A34A',
      warning: '#D97706',
      error: '#DC2626',
      info: '#0284C7',
      headerBackground: '#16A34A',
      headerText: '#FFFFFF',
      buttonPrimary: '#16A34A',
      buttonSecondary: '#BBF7D0',
      buttonText: '#FFFFFF',
      buttonTextSecondary: '#14532D',
      inputBackground: '#FFFFFF',
      inputBorder: '#86EFAC',
      inputText: '#14532D',
      placeholderText: '#22C55E',
      divider: '#86EFAC',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.5)',
      cardShadow: '#22C55E',
      toolbarBackground: '#FFFFFF',
      toolbarBorder: '#86EFAC',
      alternateBackground: '#F7FEE7',
    },
    dark: {
      text: '#BBF7D0',
      background: '#14532D',
      tint: '#4ADE80',
      icon: '#86EFAC',
      tabIconDefault: '#22C55E',
      tabIconSelected: '#4ADE80',
      primary: '#22C55E',
      secondary: '#15803D',
      accent: '#16A34A',
      card: '#15803D',
      border: '#166534',
      notification: '#FCA5A5',
      success: '#4ADE80',
      warning: '#FCD34D',
      error: '#FCA5A5',
      info: '#7DD3FC',
      headerBackground: '#14532D',
      headerText: '#BBF7D0',
      buttonPrimary: '#22C55E',
      buttonSecondary: '#15803D',
      buttonText: '#BBF7D0',
      buttonTextSecondary: '#BBF7D0',
      inputBackground: '#15803D',
      inputBorder: '#166534',
      inputText: '#BBF7D0',
      placeholderText: '#22C55E',
      divider: '#166534',
      shadow: '#000000',
      overlay: 'rgba(0, 0, 0, 0.7)',
      cardShadow: '#14532D',
      toolbarBackground: '#15803D',
      toolbarBorder: '#166534',
      alternateBackground: '#166534',
    }
  }
};

// للتوافق مع الكود الموجود
export const Colors = Themes.default;

// أنماط موحدة للتطبيق
export const GlobalStyles = {
  // أنماط الهيدر
  header: {
    backgroundColor: Colors.light.headerBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold' as const,
    color: Colors.light.headerText,
    textAlign: 'center' as const,
    flex: 1,
    writingDirection: 'rtl' as const,
  },
  headerButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },

  // أنماط الأزرار
  primaryButton: {
    backgroundColor: Colors.light.buttonPrimary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  secondaryButton: {
    backgroundColor: Colors.light.buttonSecondary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  primaryButtonText: {
    color: Colors.light.buttonText,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },
  secondaryButtonText: {
    color: Colors.light.buttonTextSecondary,
    fontSize: 16,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط البطاقات
  card: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    shadowColor: Colors.light.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },

  // أنماط المدخلات
  textInput: {
    backgroundColor: Colors.light.inputBackground,
    borderWidth: 1,
    borderColor: Colors.light.inputBorder,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: Colors.light.inputText,
    textAlign: 'right' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط شريط الأدوات
  toolbar: {
    flexDirection: 'row' as const,
    backgroundColor: Colors.light.toolbarBackground,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.toolbarBorder,
    gap: 5,
  },
  toolButton: {
    flex: 1,
    alignItems: 'center' as const,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 8,
    backgroundColor: Colors.light.alternateBackground,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  toolButtonText: {
    fontSize: 10,
    color: Colors.light.text,
    marginTop: 2,
    textAlign: 'center' as const,
    fontWeight: '500' as const,
    writingDirection: 'rtl' as const,
  },

  // أنماط عامة
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.light.divider,
    marginVertical: 16,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: Colors.light.placeholderText,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
  },
};